version: 2
jobs:
  build:
    working_directory: ~/jinahya-springframework
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: jinahya-springframework-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: jinahya-springframework-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
#      - store_artifacts:
#          path: target/bit-io/



